/*
 * One-off: downloads the Google Fonts used by the site (latin + latin-ext
 * subsets) into ./fonts and writes ./fonts/fonts.css with local @font-face.
 * Run: node fetch-fonts.js
 */
const fs = require('fs');
const path = require('path');

const CSS_URL = 'https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,300;0,400;0,500;0,600;1,400&family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&family=Bricolage+Grotesque:wght@400..800&display=swap';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const KEEP = ['latin', 'latin-ext'];
const OUT = 'fonts';

(async () => {
  fs.mkdirSync(OUT, { recursive: true });
  const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

  // Split into "/* subset */ @font-face {...}" chunks
  const parts = css.split(/\/\*\s*([\w-]+)\s*\*\//).slice(1); // [subset, block, subset, block, ...]

  // Google serves variable fonts: every weight of a family/style/subset points at the SAME file.
  // Group by URL so each file is downloaded once and declared once with a weight range —
  // otherwise browsers fetch identical files under different names (was ~1 MB of duplicates).
  const byUrl = new Map();
  for (let i = 0; i < parts.length; i += 2) {
    const subset = parts[i].trim();
    const block = parts[i + 1];
    if (!KEEP.includes(subset)) continue;

    const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
    const style = (block.match(/font-style:\s*(\w+)/) || [])[1];
    // Google sends either one weight ("400") or a variable range ("400 800") — keep both ends
    const wm = block.match(/font-weight:\s*(\d+)(?:\s+(\d+))?/) || [];
    const weights = [Number(wm[1])].concat(wm[2] ? [Number(wm[2])] : []);
    const url = (block.match(/src:\s*url\(([^)]+)\)/) || [])[1];
    const range = (block.match(/unicode-range:\s*([^;]+);/) || [])[1];
    if (!fam || !url) continue;

    const g = byUrl.get(url) || { fam, style, subset, range, weights: [] };
    g.weights.push.apply(g.weights, weights);
    byUrl.set(url, g);
  }

  let outCss = '/* Self-hosted fonts — generated by fetch-fonts.js (one file per family/style/subset) */\n';
  for (const [url, g] of byUrl) {
    const slug = g.fam.toLowerCase().replace(/\s+/g, '') + '-' + g.style + '-' + g.subset + '.woff2';
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(OUT, slug), buf);
    const lo = Math.min(...g.weights), hi = Math.max(...g.weights);
    outCss += "@font-face {\n  font-family: '" + g.fam + "';\n  font-style: " + g.style + ";\n  font-weight: " +
      (lo === hi ? lo : lo + ' ' + hi) + ";\n  font-display: swap;\n  src: url(/fonts/" + slug + ") format('woff2');\n" +
      (g.range ? '  unicode-range: ' + g.range + ';\n' : '') + '}\n\n';
    console.log('  ' + slug + '  weights ' + g.weights.join('/') + '  (' + buf.length + ' bytes)');
  }

  fs.writeFileSync(path.join(OUT, 'fonts.css'), outCss, 'utf8');
  console.log('Done: ' + byUrl.size + ' files + fonts/fonts.css');
})();
