/*
 * One-off: downloads the Google Fonts used by the site (latin + latin-ext
 * subsets) into ./fonts and writes ./fonts/fonts.css with local @font-face.
 * Run: node fetch-fonts.js
 */
const fs = require('fs');
const path = require('path');

const CSS_URL = 'https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,300;0,400;0,500;0,600;1,400&family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const KEEP = ['latin', 'latin-ext'];
const OUT = 'fonts';

(async () => {
  fs.mkdirSync(OUT, { recursive: true });
  const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

  // Split into "/* subset */ @font-face {...}" chunks
  const parts = css.split(/\/\*\s*([\w-]+)\s*\*\//).slice(1); // [subset, block, subset, block, ...]
  let outCss = '/* Self-hosted fonts — generated by fetch-fonts.js */\n';
  let n = 0;

  for (let i = 0; i < parts.length; i += 2) {
    const subset = parts[i].trim();
    const block = parts[i + 1];
    if (!KEEP.includes(subset)) continue;

    const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
    const style = (block.match(/font-style:\s*(\w+)/) || [])[1];
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1];
    const url = (block.match(/src:\s*url\(([^)]+)\)/) || [])[1];
    if (!fam || !url) continue;

    const slug = fam.toLowerCase().replace(/\s+/g, '') + '-' + weight + '-' + style + '-' + subset + '.woff2';
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(OUT, slug), buf);
    n++;

    outCss += block.replace(/src:\s*url\([^)]+\)\s*format\('woff2'\);/, "src: url(/fonts/" + slug + ") format('woff2');").trim() + '\n\n';
    console.log('  ' + slug + '  (' + buf.length + ' bytes)');
  }

  fs.writeFileSync(path.join(OUT, 'fonts.css'), outCss, 'utf8');
  console.log('Done: ' + n + ' files + fonts/fonts.css');
})();
